### PR TITLE
Upgrade to karaf 4.x

### PR DESCRIPTION
**Pull request by gnodet**

### CODE REVIEW

**Comment by gnodet** [comment]
The windows batch file needs to be adjusted in a similar way than the unix shell script.

**Comment by gnodet** [comment]
This PR is related to #38, but it's currently using the shell-compatibility layer to avoid disruptive changed. The next step is definitely to switch the commands to the new API and to leverage the karaf  maven plugin to let it create the assembly.  But all this can be done step by step.

**Comment by nacx** [comment]
Many thanks @gnodet!

>but it's currently using the shell-compatibility layer to avoid disruptive changed. The next step is definitely to switch the commands to the new API and to leverage the karaf maven plugin to let it create the assembly. But all this can be done step by step.

Absolutely.

I've tested this change build on top of the jclouds-karaf PR branch and the shell script works fine. There is just a warning about a duplicate logging class. I guess we should be able to skip the one in `lib/other`?

```bash
nacx@maqui:~/src/asf/jclouds-cli/assembly/target/jclouds-cli-2.1.0-SNAPSHOT $ bin/jclouds location list --provider digitalocean2 --identity <identity> --credential <credential>
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/nacx/src/asf/jclouds-cli/assembly/target/jclouds-cli-2.1.0-SNAPSHOT/lib/other/slf4j-log4j12-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/nacx/src/asf/jclouds-cli/assembly/target/jclouds-cli-2.1.0-SNAPSHOT/system/org/apache/karaf/org.apache.karaf.client/4.0.9/org.apache.karaf.client-4.0.9.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
[id]          [scope]  [description]                   [parent]
fra1          REGION   Frankfurt 1                     digitalocean2
sfo1          REGION   San Francisco 1                 digitalocean2
sgp1          REGION   Singapore 1                     digitalocean2
tor1          REGION   Toronto 1                       digitalocean2
ams2          REGION   Amsterdam 2                     digitalocean2
ams3          REGION   Amsterdam 3                     digitalocean2
nyc2          REGION   New York 2                      digitalocean2
nyc1          REGION   New York 1                      digitalocean2
nyc3          REGION   New York 3                      digitalocean2
lon1          REGION   London 1                        digitalocean2
blr1          REGION   Bangalore 1                     digitalocean2
digitalocean2 PROVIDER https://api.digitalocean.com/v2 <evalution error - see log>
sfo2          REGION   San Francisco 2                 digitalocean2
```

The interactive shell, however, fails to load with the following error (I haven't found more detailed logs):

```bash
nacx@maqui:~/src/asf/jclouds-cli/assembly/target/jclouds-cli-2.1.0-SNAPSHOT $ bin/jclouds-cli
Error installing bundle listed in startup.properties with url: org/ops4j/pax/url/pax-url-mvn/1.3.7/pax-url-mvn-1.3.7.jar and startlevel: 5
Exception in thread "main" java.lang.NullPointerException
	at org.apache.karaf.main.Main.destroy(Main.java:634)
	at org.apache.karaf.main.Main.main(Main.java:183)
```

**Comment by nacx** [comment]
Many thanks, @gnodet! Both versions, shell and interactive are working now. I've added the `feature` feature to the boot features to be able to install other jclouds providers in the interactive shell via `feature:install`. I assume this is correct?

```diff
diff --git a/assembly/src/main/filtered-resources/etc/org.apache.karaf.features.cfg b/assembly/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
index 5d084c1..b43aa0a 100644
--- a/assembly/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
+++ b/assembly/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
@@ -16,8 +16,9 @@
 #
 featuresRepositories=\
   mvn:org.apache.karaf.features/standard/${karaf.version}/xml/features, \
-  mvn:org.apache.jclouds.karaf/jclouds-karaf/${jclouds.karaf.version}/xml/features
+  mvn:org.apache.jclouds.karaf/jclouds-karaf/${jclouds.karaf.version}/xml/features, \
+  mvn:org.apache.jclouds.karaf/jclouds-karaf-labs/${jclouds.karaf.version}/xml/features
 
 featuresBoot=\
-  shell-compat,config,log,\
-  jclouds-chef,jclouds-aws-ec2,jclouds-aws-s3
\ No newline at end of file
+  shell-compat,config,log,feature, \
+  jclouds-chef,jclouds-aws-ec2,jclouds-aws-s3
```

**Comment by gnodet** [comment]
Looks good to me.

**Comment by nacx** [comment]
Merged :) Many thanks for your great and quick support!

**Pull request merged**
